"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var STCODES;
(function (STCODES) {
    STCODES[STCODES["SUCCESS"] = 0] = "SUCCESS";
    STCODES[STCODES["QUERYEMPTY"] = 202] = "QUERYEMPTY";
    STCODES[STCODES["PRAMAERR"] = 301] = "PRAMAERR";
    STCODES[STCODES["NOTFOUND"] = 404] = "NOTFOUND";
    STCODES[STCODES["JWTAUTHERR"] = 400] = "JWTAUTHERR";
    STCODES[STCODES["PASSWORDERR"] = 411] = "PASSWORDERR";
    STCODES[STCODES["USERNAMEERR"] = 412] = "USERNAMEERR";
    STCODES[STCODES["AUTHORIZATIONLESS"] = 413] = "AUTHORIZATIONLESS";
    STCODES[STCODES["USERNOTFOUND"] = 414] = "USERNOTFOUND";
    STCODES[STCODES["EXCEPTION"] = 500] = "EXCEPTION";
    STCODES[STCODES["DATABASECOERR"] = 701] = "DATABASECOERR";
    STCODES[STCODES["DATABASEOPERR"] = 702] = "DATABASEOPERR";
})(STCODES || (STCODES = {}));
exports.default = STCODES;
//# sourceMappingURL=enums.js.map